# Site wide configuration

title: Chris Fellingham's Edtech Newsletter
locale: en_UK
description: Salutations, I work in Strategy for FutureLearn and this is my fortnightly newsletter on trends in Edtech and education
logo: site-logo.png
search: true
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Chris Fellingham
  avatar: bio-photo.jpg
  email: chris.fellingham [at] futurelearn [dot] com
  disqus-shortname:
  twitter: @chrisfellingham
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: chris-fellingham-9ab23029

